# Generated by Django 2.2.2 on 2019-07-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('url', models.URLField(max_length=2000)),
                ('read', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('fanpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.FanPage')),
            ],
        ),
    ]
